
project_id = "nqspuwzqrwamccpqwwvj"

[functions.api]
enabled = true
verify_jwt = false
import_map = "supabase/functions/api/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "supabase/functions/api/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "supabase/functions/api/*.html" ]
